# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infection', '0002_auto_20160131_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='infection.KhanUser')),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='infection.KhanUser'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='infection.Student'),
        ),
    ]
